# Generated by Django 4.0.4 on 2022-08-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0046_storagecell_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProduct',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(null=True, verbose_name='ГУИД операции')),
                ('type_operation', models.CharField(max_length=100, null=True, verbose_name='Тип операции')),
                ('number_operation', models.CharField(max_length=100, null=True, verbose_name='Номер операции')),
                ('external_source', models.CharField(max_length=100, null=True, verbose_name='Наименование внешнего источника')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('count', models.PositiveIntegerField(default=0.0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Номенклатура операции',
                'verbose_name_plural': 'Номенклатура операций',
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('SHIPPED', 'Shipped'), ('ARCHIVE', 'Archive')], default='COLLECTED', max_length=20, verbose_name='Статус')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('content_count', models.PositiveIntegerField(default=0, verbose_name='Количество позиций внутри паллеты')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата выработки')),
                ('external_key', models.CharField(blank=True, max_length=36, null=True, verbose_name='Внешний ключ')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сборщик')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Паллета',
                'verbose_name_plural': 'Паллеты',
            },
        ),
        migrations.CreateModel(
            name='ShipmentOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.direction', verbose_name='Направление')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.shipmentoperation', verbose_name='Родительское задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отгрузка со склада',
                'verbose_name_plural': 'Операции отгрузки со склада',
            },
        ),
        migrations.CreateModel(
            name='PlacementToCellsOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.placementtocellsoperation', verbose_name='Родительское задание')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storage', verbose_name='Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Размещение в ячейки',
                'verbose_name_plural': 'Операции размещения в ячейки',
            },
        ),
        migrations.CreateModel(
            name='PalletProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('count', models.PositiveIntegerField(default=0.0, verbose_name='Количество')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата выработки')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse_management.pallet', verbose_name='Паллета')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Номенклатура паллеты',
                'verbose_name_plural': 'Номенклатура паллет',
            },
        ),
        migrations.CreateModel(
            name='PalletContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_code', models.CharField(max_length=500, verbose_name='Код агрегации')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='warehouse_management.pallet', verbose_name='Паллета')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Код агрегации',
                'verbose_name_plural': 'Коды агрегации',
            },
        ),
        migrations.CreateModel(
            name='PalletCollectOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.palletcollectoperation', verbose_name='Родительское задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сбор паллет',
                'verbose_name_plural': 'Операции сбора паллет',
            },
        ),
        migrations.CreateModel(
            name='OrderOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.client', verbose_name='Клиент')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.orderoperation', verbose_name='Родительское задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
            },
        ),
        migrations.CreateModel(
            name='OperationPallet',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(null=True, verbose_name='ГУИД операции')),
                ('type_operation', models.CharField(max_length=100, null=True, verbose_name='Тип операции')),
                ('number_operation', models.CharField(max_length=100, null=True, verbose_name='Номер операции')),
                ('external_source', models.CharField(max_length=100, null=True, verbose_name='Наименование внешнего источника')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета')),
            ],
            options={
                'verbose_name': 'Паллета операции',
                'verbose_name_plural': 'Паллеты операций',
            },
        ),
        migrations.CreateModel(
            name='MovementBetweenCellsOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.movementbetweencellsoperation', verbose_name='Родительское задание')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storage', verbose_name='Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перемещение между ячейками',
                'verbose_name_plural': 'Операции перемещения между ячейками',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата выработки')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.acceptanceoperation', verbose_name='Родительское задание')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storage', verbose_name='Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приемка на склад',
                'verbose_name_plural': 'Операции приемки товаров',
            },
        ),
        migrations.CreateModel(
            name='OperationCell',
            fields=[
                ('operationproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehouse_management.operationproduct')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_cell', to='catalogs.storagecell', verbose_name='Складская ячейка')),
                ('changed_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storagecell', verbose_name='Измененная ячейка')),
            ],
            options={
                'verbose_name': 'Складские ячейки операции',
                'verbose_name_plural': 'Складские ячейки операций',
            },
            bases=('warehouse_management.operationproduct',),
        ),
    ]
