# Generated by Django 4.0.4 on 2022-05-31 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0041_rename_activation_code_device_activation_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('is_single_product', models.BooleanField(default=True, verbose_name='Содержит товары одного вида')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Паллета',
                'verbose_name_plural': 'Паллеты',
            },
        ),
        migrations.CreateModel(
            name='PalletAggregationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_code', models.CharField(max_length=500, verbose_name='Код агрегации')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='warehouse_management.pallet', verbose_name='Паллета')),
            ],
            options={
                'verbose_name': 'Код агрегации',
                'verbose_name_plural': 'Коды агрегации',
            },
        ),
    ]
