# Generated by Django 4.0.4 on 2022-06-10 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0043_storage_store_semi_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('SHIPPED', 'Shipped')], default='COLLECTED', max_length=20, verbose_name='Статус')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('content_count', models.PositiveIntegerField(default=0, verbose_name='Количество позиций внутри паллеты')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сборщик')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Паллета',
                'verbose_name_plural': 'Паллеты',
            },
        ),
        migrations.CreateModel(
            name='PalletContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_code', models.CharField(max_length=500, verbose_name='Код агрегации')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='warehouse_management.pallet', verbose_name='Паллета')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Код агрегации',
                'verbose_name_plural': 'Коды агрегации',
            },
        ),
        migrations.CreateModel(
            name='PalletCollectOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.palletcollectoperation', verbose_name='Родительское задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сбор паллет',
                'verbose_name_plural': 'Операции сбора паллет',
            },
        ),
        migrations.CreateModel(
            name='OperationProduct',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(null=True, verbose_name='ГУИД операции')),
                ('type_operation', models.CharField(max_length=100, null=True, verbose_name='Тип операции')),
                ('number_operation', models.CharField(max_length=100, null=True, verbose_name='Номер операции')),
                ('external_source', models.CharField(max_length=100, null=True, verbose_name='Наименование внешнего источника')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('count', models.PositiveIntegerField(default=0.0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Номенклатура операции',
                'verbose_name_plural': 'Номенклатура операций',
            },
        ),
        migrations.CreateModel(
            name='OperationPallet',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(null=True, verbose_name='ГУИД операции')),
                ('type_operation', models.CharField(max_length=100, null=True, verbose_name='Тип операции')),
                ('number_operation', models.CharField(max_length=100, null=True, verbose_name='Номер операции')),
                ('external_source', models.CharField(max_length=100, null=True, verbose_name='Наименование внешнего источника')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета')),
            ],
            options={
                'verbose_name': 'Паллета операции',
                'verbose_name_plural': 'Паллеты операций',
            },
        ),
        migrations.CreateModel(
            name='MovementOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.movementoperation', verbose_name='Родительское задание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перемещение товаров',
                'verbose_name_plural': 'Операции перемещения товаров',
            },
        ),
    ]
