# Generated by Django 4.0.4 on 2022-06-01 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0041_rename_activation_code_device_activation_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_code', models.CharField(max_length=500, verbose_name='Код агрегации')),
            ],
            options={
                'verbose_name': 'Код агрегации',
                'verbose_name_plural': 'Коды агрегации',
            },
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='is_single_product',
        ),
        migrations.AddField(
            model_name='pallet',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сборщик'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='content_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество позиций внутри паллеты'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('SHIPPED', 'Shipped')], default='COLLECTED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
        migrations.DeleteModel(
            name='PalletAggregationCode',
        ),
        migrations.AddField(
            model_name='palletcontent',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='warehouse_management.pallet', verbose_name='Паллета'),
        ),
        migrations.AddField(
            model_name='palletcontent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура'),
        ),
    ]
