# Generated by Django 4.0.4 on 2022-06-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выработки'),
        ),
    ]
