# Generated by Django 4.0.4 on 2022-08-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0046_storagecell_barcode'),
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Номенклатура'),
        ),
    ]
