# Generated by Django 4.0.4 on 2022-06-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0043_storage_store_semi_product'),
        ('warehouse_management', '0002_pallet_production_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementoperation',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выработки'),
        ),
        migrations.AddField(
            model_name='movementoperation',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.storage', verbose_name='Склад'),
        ),
    ]
