# Generated by Django 4.0.4 on 2022-08-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0002_alter_palletproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptanceoperation',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='movementbetweencellsoperation',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='orderoperation',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='palletcollectoperation',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='placementtocellsoperation',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='shipmentoperation',
            name='parent_task',
        ),
    ]
