# Generated by Django 4.0.4 on 2022-08-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0003_remove_acceptanceoperation_parent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoperation',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.shipmentoperation', verbose_name='Родительское задание'),
        ),
    ]
