# Generated by Django 4.0.4 on 2022-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0004_rename_movementoperation_acceptanceoperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceoperation',
            name='batch_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии'),
        ),
    ]
