# Generated by Django 4.0.4 on 2022-08-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0047_alter_externalsource_external_key_and_more'),
        ('warehouse_management', '0004_orderoperation_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('SHIPPED', 'Shipped'), ('ARCHIVE', 'Archive'), ('WAIT', 'Wait')], default='COLLECTED', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PalletSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('count', models.PositiveIntegerField(default=0.0, verbose_name='Количество')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата выработки')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='warehouse_management.pallet', verbose_name='Паллета')),
                ('pallet_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета источник')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Паллета источник',
                'verbose_name_plural': 'Паллеты источники',
            },
        ),
    ]
