# Generated by Django 4.0.4 on 2022-06-18 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0044_storagecell_alter_activationkey_options_and_more'),
        ('warehouse_management', '0005_acceptanceoperation_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementToCellsOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.placementtocellsoperation', verbose_name='Родительское задание')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.storage', verbose_name='Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Размещение в ячейки',
                'verbose_name_plural': 'Операции размещения в ячейки',
            },
        ),
        migrations.CreateModel(
            name='OperationCell',
            fields=[
                ('operationproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehouse_management.operationproduct')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.storagecell', verbose_name='Складская ячейка')),
            ],
            options={
                'verbose_name': 'Складские ячейки операции',
                'verbose_name_plural': 'Складские ячейки операций',
            },
            bases=('warehouse_management.operationproduct',),
        ),
    ]
