# Generated by Django 4.0.4 on 2022-08-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0006_rename_changed_cell_operationcell_cell_destination_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationCell',
        ),
    ]
