# Generated by Django 4.0.4 on 2022-06-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0045_alter_storage_options'),
        ('warehouse_management', '0006_placementtocellsoperation_operationcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtocellsoperation',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_cell', to='catalogs.storagecell', verbose_name='Ячейка'),
        ),
        migrations.AddField(
            model_name='placementtocellsoperation',
            name='changed_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storagecell', verbose_name='Измененная ячейка'),
        ),
        migrations.AddField(
            model_name='placementtocellsoperation',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='placementtocellsoperation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Номенклатура'),
        ),
    ]
