# Generated by Django 4.0.4 on 2022-06-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0045_alter_storage_options'),
        ('warehouse_management', '0007_placementtocellsoperation_cell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementtocellsoperation',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='placementtocellsoperation',
            name='changed_cell',
        ),
        migrations.RemoveField(
            model_name='placementtocellsoperation',
            name='count',
        ),
        migrations.RemoveField(
            model_name='placementtocellsoperation',
            name='product',
        ),
        migrations.AddField(
            model_name='operationcell',
            name='changed_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storagecell', verbose_name='Измененная ячейка'),
        ),
        migrations.AlterField(
            model_name='operationcell',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_cell', to='catalogs.storagecell', verbose_name='Складская ячейка'),
        ),
    ]
