# Generated by Django 4.0.4 on 2022-08-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0007_delete_operationcell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderoperation',
            options={'verbose_name': 'Заказ клиента', 'verbose_name_plural': 'Отгрузка со склада (Заказы клиентов)'},
        ),
        migrations.AlterModelOptions(
            name='shipmentoperation',
            options={'verbose_name': 'Отгрузка со склада', 'verbose_name_plural': 'Отгрузка со со склада (Заявка на завод)'},
        ),
    ]
