# Generated by Django 4.0.4 on 2022-08-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0009_operationcell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptanceoperation',
            options={'verbose_name': 'Приемка на склад', 'verbose_name_plural': 'Приемка товаров'},
        ),
        migrations.AlterModelOptions(
            name='movementbetweencellsoperation',
            options={'verbose_name': 'Перемещение между ячейками', 'verbose_name_plural': 'Перемещения между ячейками'},
        ),
        migrations.AlterModelOptions(
            name='palletcollectoperation',
            options={'verbose_name': 'Сбор паллет', 'verbose_name_plural': 'Сбор паллет'},
        ),
        migrations.AlterModelOptions(
            name='placementtocellsoperation',
            options={'verbose_name': 'Размещение в ячейки', 'verbose_name_plural': 'Размещения в ячейки'},
        ),
    ]
