# Generated by Django 4.0.4 on 2022-08-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0046_storagecell_barcode'),
        ('warehouse_management', '0010_alter_acceptanceoperation_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoperation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.client', verbose_name='Клиент'),
        ),
    ]
