# Generated by Django 4.0.4 on 2022-08-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0010_alter_acceptanceoperation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationcell',
            name='count',
        ),
        migrations.RemoveField(
            model_name='operationcell',
            name='product',
        ),
        migrations.RemoveField(
            model_name='operationcell',
            name='weight',
        ),
        migrations.AddField(
            model_name='operationcell',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета'),
        ),
        migrations.AlterField(
            model_name='operationcell',
            name='type_operation',
            field=models.CharField(default='-', max_length=100, verbose_name='Тип операции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationpallet',
            name='type_operation',
            field=models.CharField(max_length=100, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='operationproduct',
            name='type_operation',
            field=models.CharField(max_length=100, verbose_name='Тип операции'),
        ),
    ]
