# Generated by Django 4.0.4 on 2022-08-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0047_alter_externalsource_external_key_and_more'),
        ('warehouse_management', '0011_remove_operationcell_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='production_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.storage', verbose_name='Цех производства'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('SHIPPED', 'Shipped'), ('ARCHIVED', 'Archived'), ('WAITED', 'Waited'), ('FOR_SHIPMENT', 'For Shipment')], default='COLLECTED', max_length=20, verbose_name='Статус'),
        ),
    ]
