# Generated by Django 4.0.4 on 2022-08-03 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0046_storagecell_barcode'),
        ('warehouse_management', '0011_orderoperation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptanceoperation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='movementbetweencellsoperation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderoperation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='palletcollectoperation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='placementtocellsoperation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='shipmentoperation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PalletProduct',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(null=True, verbose_name='ГУИД операции')),
                ('type_operation', models.CharField(max_length=100, null=True, verbose_name='Тип операции')),
                ('number_operation', models.CharField(max_length=100, null=True, verbose_name='Номер операции')),
                ('external_source', models.CharField(max_length=100, null=True, verbose_name='Наименование внешнего источника')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес')),
                ('count', models.PositiveIntegerField(default=0.0, verbose_name='Количество')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата выработки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Номенклатура паллеты',
                'verbose_name_plural': 'Номенклатура паллет',
            },
        ),
    ]
