# Generated by Django 4.0.4 on 2022-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0015_orderoperation_client_presentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletproduct',
            name='has_shipped_products',
            field=models.BooleanField(default=False, verbose_name='Содержит номенклатуру требующую обеспечения'),
        ),
    ]
