# Generated by Django 4.0.4 on 2022-09-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0016_palletproduct_has_shipped_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='has_shipped_products',
        ),
    ]
