# Generated by Django 4.0.4 on 2022-09-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0017_remove_pallet_has_shipped_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletproduct',
            name='is_collected',
            field=models.BooleanField(default=False, verbose_name='Собрано'),
        ),
    ]
