# Generated by Django 4.0.4 on 2022-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0018_palletproduct_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Идентификатор'),
        ),
    ]
