# Generated by Django 4.0.4 on 2022-09-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0019_alter_pallet_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptanceoperation',
            options={'verbose_name': 'Приемка на склад', 'verbose_name_plural': 'Приемка товаров (Заказ на перемещение)'},
        ),
    ]
