# Generated by Django 4.0.4 on 2022-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0020_alter_acceptanceoperation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='marking_group',
            field=models.UUIDField(blank=True, null=True, verbose_name='Группа маркировки'),
        ),
    ]
