# Generated by Django 4.0.4 on 2022-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0021_pallet_marking_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='marking_group',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Группа маркировки'),
        ),
    ]
