# Generated by Django 4.0.4 on 2022-10-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0049_product_not_marked_and_more'),
        ('warehouse_management', '0023_alter_pallet_pallet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalAtStockOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storage', verbose_name='Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приход на склад',
                'verbose_name_plural': 'Приход на склад (Поступление товаров и услуг)',
            },
        ),
    ]
