# Generated by Django 4.0.4 on 2022-11-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0027_pallet_cell_alter_pallet_status_selectionoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletcollectoperation',
            name='parent_task',
        ),
    ]
