# Generated by Django 4.0.4 on 2022-11-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0028_remove_palletcollectoperation_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletcollectoperation',
            name='parent_task',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Родительское задание'),
        ),
        migrations.AlterField(
            model_name='palletcollectoperation',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection')], default='ACCEPTANCE', max_length=255, verbose_name='Тип сбора'),
        ),
    ]
