# Generated by Django 4.0.4 on 2022-11-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0029_palletcollectoperation_parent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentoperation',
            name='has_selection',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Есть отбор'),
        ),
    ]
