# Generated by Django 4.0.4 on 2022-11-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0050_product_variable_pallet_weight'),
        ('warehouse_management', '0030_shipmentoperation_has_selection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectionoperation',
            options={'verbose_name': 'Отбор со склада', 'verbose_name_plural': 'Отбор со склада (Заявка на завод)'},
        ),
        migrations.AlterModelOptions(
            name='shipmentoperation',
            options={'verbose_name': 'Отгрузка со склада', 'verbose_name_plural': 'Отгрузка со склада (Заявка на завод)'},
        ),
        migrations.AlterField(
            model_name='operationcell',
            name='cell_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storagecell', verbose_name='Ячейка (назначение / измененная)'),
        ),
    ]
