# Generated by Django 4.0.4 on 2022-12-22 10:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0032_alter_pallet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCell',
            fields=[
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ')),
                ('barcode', models.CharField(default='-', max_length=100, verbose_name='Штрихкод')),
            ],
            options={
                'verbose_name': 'Складская ячейка',
                'verbose_name_plural': 'Складские ячейки',
            },
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='cell',
        ),
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted'), ('SHIPPED', 'Shipped'), ('ARCHIVED', 'Archived'), ('WAITED', 'Waited'), ('FOR_SHIPMENT', 'For Shipment'), ('SELECTED', 'Selected'), ('PLACED', 'Placed'), ('FOR_REPACKING', 'For Repacking')], default='COLLECTED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='operationcell',
            name='cell_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_management.storagecell', verbose_name='Ячейка (назначение / измененная)'),
        ),
        migrations.AlterField(
            model_name='operationcell',
            name='cell_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_cell', to='warehouse_management.storagecell', verbose_name='Складская ячейка'),
        ),
    ]
