# Generated by Django 4.0.4 on 2022-12-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0034_storagearea_storagecell_storage_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCellContentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creating_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('REMOVED', 'Removed')], default='PLACED', max_length=20, verbose_name='Статус')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.storagecell', verbose_name='Ячейка')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета')),
            ],
        ),
    ]
