# Generated by Django 4.0.4 on 2022-12-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0035_storagecellcontentstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagecellcontentstate',
            options={'verbose_name': 'Состояние складских ячеек', 'verbose_name_plural': 'Состояние складских ячеек'},
        ),
    ]
