# Generated by Django 4.0.4 on 2023-01-08 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0051_delete_storagecell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse_management', '0036_alter_storagecellcontentstate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pallet_type',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('FULLED', 'Fulled'), ('COMBINED', 'Combined'), ('TASK', 'Task')], default='FULLED', max_length=50, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='RepackingOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Переупаковка',
                'verbose_name_plural': 'Переупаковка',
            },
        ),
    ]
