# Generated by Django 4.0.4 on 2023-01-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0037_alter_pallet_pallet_type_repackingoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationpallet',
            name='dependent_pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depended_pallets', to='warehouse_management.pallet', verbose_name='Зависимая паллета'),
        ),
        migrations.AlterField(
            model_name='operationpallet',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_pallets', to='warehouse_management.pallet', verbose_name='Паллета'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='pallet_type',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('FULLED', 'Fulled'), ('COMBINED', 'Combined'), ('REPACKING', 'Repacking')], default='FULLED', max_length=50, verbose_name='Тип'),
        ),
    ]
