# Generated by Django 4.0.4 on 2023-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0038_operationpallet_dependent_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationpallet',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество'),
        ),
    ]
