# Generated by Django 4.0.4 on 2023-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0040_pallet_not_fully_collected_palletsource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecell',
            name='needed_scan',
            field=models.BooleanField(default=True, verbose_name='Необходимо сканировать при размещении'),
        ),
    ]
