# Generated by Django 4.0.4 on 2023-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0041_storagecell_needed_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletproduct',
            name='has_divergence',
            field=models.BooleanField(default=False, verbose_name='Имеет расхождение'),
        ),
    ]
