# Generated by Django 4.0.4 on 2023-01-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0043_operationpallet_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationpallet',
            name='weight',
        ),
    ]
