# Generated by Django 4.0.4 on 2023-02-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0044_remove_operationpallet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='external_task_key',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Ключ внешнего задания'),
        ),
    ]
