# Generated by Django 4.0.4 on 2023-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0045_pallet_external_task_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecell',
            name='needed_filter_by_task',
            field=models.BooleanField(default=False, verbose_name='Необходим фильтр по задания при размещении'),
        ),
    ]
