# Generated by Django 4.0.4 on 2023-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0046_storagecell_needed_filter_by_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentoperation',
            name='direction',
        ),
        migrations.AddField(
            model_name='pallet',
            name='consignee',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Грузополучатель'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='shipmentoperation',
            name='manager',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Менеджер'),
        ),
    ]
