# Generated by Django 4.0.4 on 2023-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0047_remove_shipmentoperation_direction_pallet_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentoperation',
            name='direction',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Направление'),
        ),
    ]
