# Generated by Django 4.0.4 on 2023-03-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0048_shipmentoperation_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletsource',
            name='additional_collect',
            field=models.BooleanField(blank=True, default=False, verbose_name='Дополнение к заданию'),
        ),
        migrations.AddField(
            model_name='storagecell',
            name='rack_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер стеллажа'),
        ),
    ]
