# Generated by Django 4.0.4 on 2023-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0049_palletsource_additional_collect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecell',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция внутри стеллажа'),
        ),
    ]
