# Generated by Django 4.0.4 on 2023-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0051_storagearea_use_for_automatic_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='series',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='palletproduct',
            name='series',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Серия'),
        ),
    ]
