# Generated by Django 4.0.4 on 2023-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0052_pallet_series_palletproduct_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentoperation',
            name='car_carrier',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Машина перевозчик'),
        ),
    ]
