# Generated by Django 4.0.4 on 2023-03-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0053_shipmentoperation_car_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitablePallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('priority', models.PositiveIntegerField(verbose_name='Приоритет')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета')),
                ('pallet_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.palletproduct', verbose_name='Строка товаров')),
            ],
            options={
                'verbose_name': 'Подходящие паллеты',
                'verbose_name_plural': 'Подходящие паллеты (посторчная выгрузка)',
            },
        ),
    ]
