# Generated by Django 4.0.4 on 2023-04-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0057_palletsource_related_task_palletsource_type_collect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletsource',
            name='pallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='warehouse_management.pallet', verbose_name='Паллета'),
        ),
    ]
