# Generated by Django 4.0.4 on 2023-05-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0058_alter_palletsource_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletcollectoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
    ]
