# Generated by Django 4.0.4 on 2023-05-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0052_unit_weight'),
        ('warehouse_management', '0059_palletcollectoperation_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAddressWarehouseOperation',
            fields=[
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORK', 'Work'), ('WAIT', 'Wait'), ('CLOSE', 'Close')], default='NEW', max_length=255, verbose_name='Статус')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.externalsource', verbose_name='Внешний источник')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инвентаризация адресного склада',
                'verbose_name_plural': 'Инвентаризация адресного склада',
            },
        ),
        migrations.CreateModel(
            name='InventoryAddressWarehouseContent',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.UUIDField(null=True, verbose_name='ГУИД операции')),
                ('type_operation', models.CharField(max_length=100, verbose_name='Тип операции')),
                ('number_operation', models.CharField(max_length=100, null=True, verbose_name='Номер операции')),
                ('external_source', models.CharField(max_length=100, null=True, verbose_name='Наименование внешнего источника')),
                ('plan', models.PositiveIntegerField(default=0.0, verbose_name='Количество (план)')),
                ('fact', models.PositiveIntegerField(default=0.0, verbose_name='Количество (факт)')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.storagecell', verbose_name='Складская ячейка')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.pallet', verbose_name='Паллета')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Инвентаризация адресного склада (Содержимое операции)',
                'verbose_name_plural': 'Инвентаризация адресного склада (Содержимое операции)',
            },
        ),
    ]
