# Generated by Django 4.0.4 on 2023-05-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0061_writeoffoperation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletcollectoperation',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory')], default='ACCEPTANCE', max_length=255, verbose_name='Тип сбора'),
        ),
        migrations.AlterField(
            model_name='palletsource',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory')], default='SHIPMENT', max_length=255, verbose_name='Тип сбора'),
        ),
    ]
