# Generated by Django 4.0.4 on 2023-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0062_alter_palletcollectoperation_type_collect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletcollectoperation',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory'), ('DIVIDED', 'Divided')], default='ACCEPTANCE', max_length=255, verbose_name='Тип сбора'),
        ),
        migrations.AlterField(
            model_name='palletsource',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory'), ('DIVIDED', 'Divided')], default='SHIPMENT', max_length=255, verbose_name='Тип сбора'),
        ),
    ]
