# Generated by Django 4.0.4 on 2023-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0065_alter_pallet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='group',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Группа паллет'),
        ),
    ]
