# Generated by Django 4.0.4 on 2023-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0067_pallet_initial_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='initial_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Исходное количество ящиков'),
        ),
    ]
