# Generated by Django 4.0.4 on 2023-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0069_alter_suitablepallets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
