# Generated by Django 4.0.4 on 2023-09-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0070_cancelshipmentoperation'),
        ('warehouse_management', '0070_palletsource_created_at'),
    ]

    operations = [
    ]
