# Generated by Django 4.0.4 on 2023-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0072_movementshipmentoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaddresswarehousecontent',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Приоритет сортировки'),
        ),
    ]
