# Generated by Django 4.0.4 on 2023-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0073_inventoryaddresswarehousecontent_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecell',
            name='id_area',
            field=models.CharField(choices=[('FOR SHIPMENT', 'For Shipment'), ('REPLACEMENT', 'Replacement')], max_length=20, null=True, verbose_name='Идентификатор области'),
        ),
    ]
