# Generated by Django 4.0.4 on 2023-11-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0074_storagecell_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='arrivalatstockoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='cancelshipmentoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='inventoryaddresswarehouseoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='movementbetweencellsoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='movementshipmentoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='orderoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='placementtocellsoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='repackingoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='selectionoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='shipmentoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AddField(
            model_name='writeoffoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
    ]
