# Generated by Django 4.0.4 on 2023-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0074_storagecell_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaddresswarehousecontent',
            name='weight',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Вес'),
        ),
    ]
