# Generated by Django 4.0.4 on 2023-11-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0075_acceptanceoperation_modified_and_more'),
        ('warehouse_management', '0075_inventoryaddresswarehousecontent_weight'),
    ]

    operations = [
    ]
