# Generated by Django 4.0.4 on 2023-11-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse_management', '0075_acceptanceoperation_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletcollectoperation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='storagecell',
            name='id_area',
            field=models.CharField(choices=[('FOR_SHIPMENT', 'For Shipment'), ('REPLACEMENT', 'Replacement')], max_length=20, null=True, verbose_name='Идентификатор области'),
        ),
    ]
