# Generated by Django 4.0.4 on 2023-11-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0076_merge_20231122_0940'),
        ('warehouse_management', '0076_palletcollectoperation_manager_and_more'),
    ]

    operations = [
    ]
