# Generated by Django 4.0.4 on 2024-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0077_merge_20231129_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionoperation',
            name='subtype_task',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory'), ('DIVIDED', 'Divided'), ('MOVEMENT', 'Movement')], default='SELECTION', max_length=67, null=True, verbose_name='Тип отбора'),
        ),
        migrations.AddField(
            model_name='shipmentoperation',
            name='subtype_task',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory'), ('DIVIDED', 'Divided'), ('MOVEMENT', 'Movement')], default='SHIPMENT', editable=False, max_length=67, null=True, verbose_name='Тип отгрузки'),
        ),
        migrations.AlterField(
            model_name='palletcollectoperation',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory'), ('DIVIDED', 'Divided'), ('MOVEMENT', 'Movement')], default='ACCEPTANCE', max_length=255, verbose_name='Тип сбора'),
        ),
        migrations.AlterField(
            model_name='palletsource',
            name='type_collect',
            field=models.CharField(choices=[('SHIPMENT', 'Shipment'), ('ACCEPTANCE', 'Acceptance'), ('SELECTION', 'Selection'), ('WRITE_OFF', 'Write Off'), ('INVENTORY', 'Inventory'), ('DIVIDED', 'Divided'), ('MOVEMENT', 'Movement')], default='SHIPMENT', max_length=255, verbose_name='Тип сбора'),
        ),
    ]
