# Generated by Django 3.2 on 2021-10-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markingoperationmarks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='markingoperationmarks',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markingoperationmarks',
            name='guid',
        ),
    ]
