# Generated by Django 3.2 on 2021-10-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingoperation',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
