# Generated by Django 3.2 on 2021-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_remove_rawmark_encoded_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingoperation',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Это новый'),
        ),
    ]
