# Generated by Django 3.2 on 2021-11-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_markingoperation_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmark',
            name='stream_splitter_code',
            field=models.PositiveIntegerField(default=0, verbose_name='Разделитель потока сканирования марок'),
        ),
    ]
