# Generated by Django 3.2 on 2021-11-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_rawmark_stream_splitter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmark',
            name='stream_splitter_code',
        ),
    ]
