# Generated by Django 3.2 on 2021-11-21 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0012_log'),
        ('packing', '0008_remove_rawmark_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectingOperation',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('number', models.IntegerField(default=1)),
                ('is_new', models.BooleanField(default=True, verbose_name='Это новый')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organization', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(max_length=500)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='packing.collectingoperation')),
            ],
        ),
    ]
