# Generated by Django 3.2 on 2021-11-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0009_collectcode_collectingoperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectcode',
            old_name='codes',
            new_name='code',
        ),
    ]
