# Generated by Django 3.2 on 2021-12-16 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0021_log_level'),
        ('packing', '0010_rename_codes_collectcode_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectingOperation',
            new_name='Pallet',
        ),
        migrations.RenameModel(
            old_name='CollectCode',
            new_name='PalletCode',
        ),
    ]
