# Generated by Django 3.2 on 2021-12-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_log_level'),
        ('packing', '0011_auto_20211216_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='identifier',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='palletcode',
            old_name='operation',
            new_name='pallet',
        ),
        migrations.AddField(
            model_name='pallet',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура'),
        ),
    ]
