# Generated by Django 3.2 on 2021-12-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0012_auto_20211216_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='number',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='ready_to_unload',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='unloaded',
        ),
    ]
