# Generated by Django 3.2 on 2021-12-17 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_log_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0014_pallet_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('ready_to_unload', models.BooleanField(default=False, verbose_name='Готова к выгрузке')),
                ('number', models.IntegerField(default=1)),
                ('is_new', models.BooleanField(default=True, verbose_name='Это новый')),
                ('type_task', models.CharField(choices=[('COLLECTING_ORDER', 'COLLECTING_ORDER')], default='COLLECTING_ORDER', max_length=255, verbose_name='Тип задания')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('WORK', 'WORK'), ('CLOSE', 'CLOSE')], default='NEW', max_length=255, verbose_name='Статус')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organization', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.task', verbose_name='Задание')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.pallet', verbose_name='Паллета')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.task', verbose_name='Задание')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='products',
            field=models.ManyToManyField(through='packing.TaskProduct', to='catalogs.Product', verbose_name='Номенклатура задания'),
        ),
        migrations.AddConstraint(
            model_name='taskproduct',
            constraint=models.UniqueConstraint(fields=('task', 'product'), name='unique_task_product'),
        ),
        migrations.AddConstraint(
            model_name='taskpallet',
            constraint=models.UniqueConstraint(fields=('task', 'pallet'), name='unique_task_pallet'),
        ),
    ]
