# Generated by Django 3.2 on 2021-12-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0015_auto_20211217_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pallets',
            field=models.ManyToManyField(through='packing.TaskPallet', to='packing.Pallet', verbose_name='Паллеты задания'),
        ),
    ]
