# Generated by Django 3.2 on 2021-12-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0016_task_pallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproduct',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес'),
        ),
    ]
