# Generated by Django 3.2 on 2021-12-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0017_taskproduct_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markingoperation',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_new',
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.CharField(choices=[('ACCEPTANCE_TO_STOCK', 'ACCEPTANCE_TO_STOCK')], default='ACCEPTANCE_TO_STOCK', max_length=255, verbose_name='Тип задания'),
        ),
    ]
