# Generated by Django 3.2 on 2022-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0019_auto_20211224_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pallets',
        ),
        migrations.RemoveField(
            model_name='task',
            name='products',
        ),
        migrations.AlterField(
            model_name='taskproduct',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес'),
        ),
    ]
