# Generated by Django 3.2 on 2022-01-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_log_level'),
        ('packing', '0020_auto_20220113_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pallets',
            field=models.ManyToManyField(through='packing.TaskPallet', to='packing.Pallet', verbose_name='Паллеты задания'),
        ),
        migrations.AddField(
            model_name='task',
            name='products',
            field=models.ManyToManyField(through='packing.TaskProduct', to='catalogs.Product', verbose_name='Номенклатура задания'),
        ),
    ]
