# Generated by Django 3.2 on 2022-01-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0022_clients_direction'),
        ('packing', '0022_task_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.clients', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='task',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.CharField(choices=[('ACCEPTANCE_TO_STOCK', 'ACCEPTANCE_TO_STOCK'), ('ORDER', 'ORDER'), ('PLANT_APPLICATION', 'PLANT_APPLICATION')], default='ACCEPTANCE_TO_STOCK', max_length=255, verbose_name='Тип задания'),
        ),
    ]
