# Generated by Django 3.2 on 2022-01-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0023_auto_20220130_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.task', verbose_name='Родительское задание'),
        ),
    ]
