# Generated by Django 3.2 on 2022-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0024_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingoperation',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Источник внешней системы'),
        ),
    ]
