# Generated by Django 3.2 on 2022-02-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0027_taskproduct_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskproduct',
            name='count',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Количество'),
        ),
    ]
