# Generated by Django 4.0.4 on 2022-05-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0028_alter_taskproduct_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletcode',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='task',
            name='client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='task',
            name='external_source',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pallets',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='products',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskpallet',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='taskpallet',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='taskproduct',
            name='task',
        ),
        migrations.DeleteModel(
            name='Pallet',
        ),
        migrations.DeleteModel(
            name='PalletCode',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskPallet',
        ),
        migrations.DeleteModel(
            name='TaskProduct',
        ),
    ]
