# Generated by Django 4.0.4 on 2022-06-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0030_alter_markingoperationmark_aggregation_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markingoperation',
            options={'verbose_name': 'Операция маркировки', 'verbose_name_plural': 'Операции маркировки'},
        ),
        migrations.AlterModelOptions(
            name='markingoperationmark',
            options={'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='rawmark',
            options={'verbose_name': 'Необработанная марка', 'verbose_name_plural': 'Необработанные марки'},
        ),
    ]
