# Generated by Django 4.0.4 on 2022-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0031_alter_markingoperation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingoperation',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
