# Generated by Django 4.0.4 on 2022-10-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0034_alter_markingoperation_group_offline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(verbose_name='Дата выработки')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
            ],
        ),
        migrations.AddField(
            model_name='markingoperation',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='markingoperation',
            name='is_offline_operation',
            field=models.BooleanField(default=False, verbose_name='Оффлайн операция'),
        ),
        migrations.AddField(
            model_name='markingoperation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.shift', verbose_name='Смена'),
        ),
    ]
