# Generated by Django 4.0.4 on 2022-10-26 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0050_product_variable_pallet_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0035_shift_markingoperation_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.line', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='markingoperation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='markingoperation',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.line', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='markingoperation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация'),
        ),
    ]
