# Generated by Django 4.0.4 on 2022-10-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0036_shift_line_alter_markingoperation_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='date',
            new_name='creating_date',
        ),
        migrations.AddField(
            model_name='shift',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
    ]
