# Generated by Django 4.0.4 on 2022-10-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0037_alter_shift_options_rename_date_shift_creating_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='code',
            field=models.UUIDField(blank=True, null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='shift',
            name='code_offline',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ключ группы оффлайн'),
        ),
    ]
