# Generated by Django 4.0.4 on 2022-10-26 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0038_shift_code_shift_code_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='id',
        ),
        migrations.AddField(
            model_name='shift',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ГУИД'),
        ),
    ]
