# Generated by Django 4.0.4 on 2022-10-26 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0039_remove_shift_code_remove_shift_id_shift_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='shift',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер'),
        ),
    ]
