# Generated by Django 4.0.4 on 2022-10-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory_core', '0001_initial'),
        ('packing', '0042_delete_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingoperation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_core.shift', verbose_name='Смена'),
        ),
    ]
