# Generated by Django 4.0.4 on 2023-11-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0044_markingoperationmark_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingoperation',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
    ]
