# Generated by Django 3.2 on 2021-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211026_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vision_controller_address',
            field=models.CharField(max_length=150, null=True, verbose_name='Контроллер тех. зрения (адрес)'),
        ),
    ]
