# Generated by Django 3.2 on 2021-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_vision_controller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vision_controller_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Контроллер тех. зрения (адрес)'),
        ),
    ]
