# Generated by Django 3.2 on 2021-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_marking_close', models.CharField(choices=[('ALL_IN_DAY_BY_LINE_BY_BAT_NUMBER', 'ALL_IN_DAY_BY_LINE_BY_BAT_NUMBER'), ('ALL_IN_DAY_BY_BAT_NUMBER', 'ALL_IN_DAY_BY_BAT_NUMBER'), ('ALL_IN_DAY_BY_LINE', 'ALL_IN_DAY_BY_LINE')], default='ALL_IN_DAY_BY_BAT_NUMBER', max_length=255)),
                ('name', models.TextField(blank=True, default='base settings')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.settings'),
        ),
    ]
