# Generated by Django 3.2 on 2021-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211121_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('INFO', 'INFO'), ('WARNING', 'WARNING')], default='ERROR', max_length=255, verbose_name='Уровень логирования'),
        ),
    ]
