# Generated by Django 3.2 on 2021-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='level',
            new_name='log_level',
        ),
        migrations.AddField(
            model_name='user',
            name='inactive_period_in_sec',
            field=models.PositiveIntegerField(default=0, verbose_name='Интервал оповещения'),
        ),
        migrations.AddField(
            model_name='user',
            name='inactive_sound_enabled',
            field=models.BooleanField(default=False, verbose_name='Включать звуковое оповещение при неактивности'),
        ),
    ]
