# Generated by Django 3.2 on 2021-12-05 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_setting_collect_pallet_mode_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_event', models.CharField(choices=[('LOG_REQUEST', 'LOG_REQUEST'), ('CUSTOM', 'CUSTOM'), ('TABLE_UPDATE', 'TABLE_UPDATE')], default='CUSTOM', max_length=255, verbose_name='Тип события')),
                ('argument', models.CharField(max_length=255, verbose_name='Параметр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceEvent',
        ),
    ]
