# Generated by Django 3.2 on 2021-12-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211205_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISION_OPERATOR', 'VISION_OPERATOR'), ('PACKER', 'PACKER'), ('PALLET_COLLECTOR', 'PALLET_COLLECTOR'), ('REJECTER', 'REJECTER'), ('SERVICE', 'SERVICE'), ('LOADER', 'LOADER')], default='PACKER', max_length=255, verbose_name='Роль'),
        ),
    ]
