# Generated by Django 4.0.4 on 2022-08-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_use_aggregations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
    ]
