# Generated by Django 4.0.4 on 2022-08-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0047_alter_externalsource_external_key_and_more'),
        ('users', '0019_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.storage', verbose_name='Цех'),
        ),
    ]
