# Generated by Django 4.0.4 on 2022-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_configevent_options_alter_setting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_timeout',
            field=models.IntegerField(default=10, verbose_name='Интервал обновления'),
        ),
    ]
