# Generated by Django 4.0.4 on 2022-10-30 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_refresh_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_send_interval',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1200)], verbose_name='Интервал отправки данных'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_timeout',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1200)], verbose_name='Интервал обновления'),
        ),
    ]
