# Generated by Django 4.0.4 on 2022-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_data_send_interval_alter_user_refresh_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_page',
            field=models.CharField(default='', max_length=100, verbose_name='Страница по умолчанию'),
        ),
    ]
