# Generated by Django 4.0.4 on 2022-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_default_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_page',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Страница по умолчанию'),
        ),
    ]
