# Generated by Django 4.0.4 on 2023-01-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_setting_label_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable_production_date_filter',
            field=models.BooleanField(default=False, verbose_name='Отключить фильтр по дате выработки'),
        ),
    ]
