# Generated by Django 4.0.4 on 2023-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_disable_production_date_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privileged_user',
            field=models.BooleanField(default=False, verbose_name='Привилегированный пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISION_OPERATOR', 'VISION_OPERATOR'), ('PACKER', 'PACKER'), ('PALLET_COLLECTOR', 'PALLET_COLLECTOR'), ('REJECTER', 'REJECTER'), ('SERVICE', 'SERVICE'), ('LOADER', 'LOADER'), ('STOREKEEPER', 'STOREKEEPER'), ('WAREHOUSE_MASTER', 'WAREHOUSE_MASTER')], default='PACKER', max_length=255, verbose_name='Роль'),
        ),
    ]
