# Generated by Django 4.0.4 on 2023-04-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_uielement_userelement_usermode_userelement_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermode',
            name='elements',
        ),
    ]
