# Generated by Django 4.0.4 on 2023-04-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_usermode_elements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userelement',
            options={'verbose_name': 'UI элементы пользовательского режма', 'verbose_name_plural': 'UI элементы пользовательского режма'},
        ),
    ]
