# Generated by Django 4.0.4 on 2023-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_userelement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_in_list',
            field=models.BooleanField(default=False, verbose_name='Показывать в списке'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inactive_sound_enabled',
            field=models.BooleanField(default=False, verbose_name='Включать звуковое оповещение при не активности'),
        ),
    ]
