# Generated by Django 4.0.4 on 2023-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_show_in_list_alter_user_inactive_sound_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='use_cache',
            field=models.BooleanField(default=False, verbose_name='Использовать кэш'),
        ),
    ]
