# Generated by Django 4.0.4 on 2023-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_setting_use_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ttl_cache',
            field=models.PositiveIntegerField(default=600, verbose_name='Время жизни кэша (сек)'),
        ),
    ]
