# Generated by Django 4.0.4 on 2023-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_setting_ttl_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='show_raw_marking',
            field=models.BooleanField(default=False, verbose_name='Отображать сырые марки на главном дашборде'),
        ),
    ]
