# Generated by Django 4.0.4 on 2023-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_setting_shift_close_show_marks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='shift_open_show_product',
            field=models.BooleanField(default=True, verbose_name='Показывать номенклатуры при открытии смены'),
        ),
        migrations.AddField(
            model_name='setting',
            name='shift_open_show_type_marking',
            field=models.BooleanField(default=True, verbose_name='Запрашивать тип маркировки при открытии смены'),
        ),
    ]
