# Generated by Django 4.0.4 on 2023-10-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_setting_shift_open_show_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='shift_open_show_product',
            field=models.BooleanField(default=False, verbose_name='Показывать номенклатуру при открытии смены'),
        ),
    ]
