# Generated by Django 4.0.4 on 2023-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_setting_shift_open_show_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='interval_control_scanning_weight',
            field=models.PositiveIntegerField(default=50, verbose_name='Интервал запроса (в штуках)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='use_control_scanning_weight',
            field=models.BooleanField(default=False, verbose_name='Включить запрос весового ШК, для контроля веса товаров с фиксированным весом'),
        ),
    ]
