# Generated by Django 3.2 on 2021-09-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.CharField(blank=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='BaseExternalModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.basemodel')),
                ('external_key', models.CharField(blank=True, max_length=36)),
            ],
            bases=('catalogs.basemodel',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.basemodel')),
                ('polling_interval', models.PositiveIntegerField()),
            ],
            bases=('catalogs.basemodel',),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('baseexternalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.baseexternalmodel')),
            ],
            bases=('catalogs.baseexternalmodel',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('baseexternalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.baseexternalmodel')),
            ],
            bases=('catalogs.baseexternalmodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseexternalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.baseexternalmodel')),
                ('gtin', models.CharField(max_length=200, verbose_name='GTIN')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Артикул')),
            ],
            bases=('catalogs.baseexternalmodel',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('baseexternalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.baseexternalmodel')),
            ],
            bases=('catalogs.baseexternalmodel',),
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024, verbose_name='Значение')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='catalogs.property')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(through='catalogs.ProductProperty', to='catalogs.Property'),
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.basemodel')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.department')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.storage')),
            ],
            bases=('catalogs.basemodel',),
        ),
    ]
