# Generated by Django 3.2 on 2021-10-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mark_reg_exp',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регулярное выражение для получения марки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP/MAC/ID'),
        ),
    ]
