# Generated by Django 3.2 on 2021-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('VISION_OPERATOR', 'VISION_OPERATOR'), ('TABLET', 'TABLET'), ('DCT', 'DCT')], default='DCT', max_length=255),
        ),
    ]
