# Generated by Django 3.2 on 2021-09-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20210930_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.device'),
        ),
        migrations.AlterField(
            model_name='line',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.storage'),
        ),
    ]
