# Generated by Django 3.2 on 2021-10-22 06:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_remove_device_polling_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFactoryOperation',
            fields=[
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
