# Generated by Django 3.2 on 2021-10-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_typefactoryoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='type_factory_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.typefactoryoperation', verbose_name='Тип пр. операции'),
        ),
    ]
