# Generated by Django 3.2 on 2021-10-05 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_line_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='external_key',
            field=models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='external_key',
            field=models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='polling_interval',
            field=models.PositiveIntegerField(verbose_name='Интервал опроса'),
        ),
        migrations.AlterField(
            model_name='line',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='line',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='line',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.storage', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='external_key',
            field=models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_key',
            field=models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='external_key',
            field=models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ'),
        ),
    ]
