# Generated by Django 3.2 on 2021-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_line_type_factory_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='devices',
        ),
        migrations.AlterField(
            model_name='line',
            name='products',
            field=models.ManyToManyField(through='catalogs.LineProduct', to='catalogs.Product', verbose_name='Номенклатура'),
        ),
    ]
