# Generated by Django 3.2 on 2021-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_weight',
            field=models.BooleanField(default=False, verbose_name='Весовой товар'),
        ),
    ]
