# Generated by Django 3.2 on 2021-11-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_product_is_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт'),
        ),
    ]
