# Generated by Django 3.2 on 2021-11-21 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_device_empty_mark_reg_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField(verbose_name='Данные лога')),
                ('device_version', models.CharField(max_length=255, verbose_name='Версия устройства')),
                ('server_version', models.CharField(max_length=255, verbose_name='Версия промежуточной')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.device', verbose_name='Устройство')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
