# Generated by Django 3.2 on 2021-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('Тех. зрение', 'Тех. зрение'), ('Планшет', 'Планшет'), ('ТСД', 'ТСД'), ('Контроллер тех. зрения', 'Контроллер тех. зрения')], default='ТСД', max_length=255),
        ),
    ]
