# Generated by Django 3.2 on 2021-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_alter_device_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('AUTO_SCANNER', 'AUTO_SCANNER'), ('TABLET', 'TABLET'), ('DCT', 'DCT'), ('VISION_CONTROLLER', 'VISION_CONTROLLER')], default='DCT', max_length=255),
        ),
    ]
