# Generated by Django 3.2 on 2021-11-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_alter_device_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
