# Generated by Django 3.2 on 2021-11-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='Данные лога')),
                ('device_version', models.CharField(max_length=255, verbose_name='Версия устройства')),
                ('server_version', models.CharField(max_length=255, verbose_name='Версия промежуточной')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.device', verbose_name='Устройство')),
            ],
        ),
    ]
