# Generated by Django 3.2 on 2021-11-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0017_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='device_version',
            new_name='app_version',
        ),
    ]
