# Generated by Django 3.2 on 2021-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_rename_device_version_log_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('INFO', 'INFO'), ('WARNING', 'WARNING')], default='ERROR', max_length=255, verbose_name='Уровень логирования'),
        ),
    ]
