# Generated by Django 3.2 on 2021-12-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0019_log_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='level',
        ),
    ]
