# Generated by Django 3.2 on 2021-12-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0020_remove_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(default='ERROR', max_length=255, verbose_name='Уровень логирования'),
        ),
    ]
