# Generated by Django 3.2 on 2022-01-30 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_log_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
