# Generated by Django 3.2 on 2022-01-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0023_auto_20220130_1747'),
        ('catalogs', '0022_clients_direction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
