# Generated by Django 3.2 on 2022-02-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0023_rename_clients_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.CharField(max_length=1024, verbose_name='Идентификатор')),
                ('number', models.CharField(max_length=1024, verbose_name='Идентификатор')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
