# Generated by Django 3.2 on 2022-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0025_rename_guid_externalsource_external_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsource',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
