# Generated by Django 3.2 on 2022-02-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0028_externalsource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsource',
            name='date',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Дата'),
        ),
    ]
