# Generated by Django 3.2 on 2022-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0029_alter_externalsource_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_expression', models.CharField(choices=[('GS1', 'GS1'), ('VISION_STREAM', 'VISION_STREAM')], default='GS1', max_length=255)),
                ('value', models.CharField(default='(01){GS1}', max_length=1024, verbose_name='Значение')),
            ],
        ),
    ]
