# Generated by Django 3.2 on 2022-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_regularexpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularexpression',
            name='type_expression',
            field=models.CharField(choices=[('AGGREGATON_CODE', 'AGGREGATON_CODE'), ('VISION_STREAM', 'VISION_STREAM')], default='AGGREGATON_CODE', max_length=255),
        ),
    ]
