# Generated by Django 3.2 on 2022-03-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0032_auto_20220315_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='empty_mark_reg_exp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='reg_exp',
        ),
    ]
