# Generated by Django 3.2 on 2022-03-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0033_remove_text_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='empty_mark_reg_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.regularexpression', verbose_name='Регулярное выражение пучтой марки'),
        ),
    ]
