# Generated by Django 3.2 on 2022-03-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0035_new_type_regexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='gtin',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='regularexpression',
            name='type_expression',
            field=models.CharField(choices=[('AGGREGATION_CODE', 'AGGREGATION_CODE'), ('MARK', 'MARK'), ('EMPTY_DATA_STREAM', 'EMPTY_DATA_STREAM')], default='AGGREGATION_CODE', max_length=255),
        ),
    ]
