# Generated by Django 3.2 on 2022-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0037_auto_20220317_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
