# Generated by Django 3.2 on 2022-03-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0038_alter_activationkey_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularexpression',
            name='activation_code',
        ),
        migrations.AddField(
            model_name='device',
            name='activation_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='catalogs.activationkey', verbose_name='Код активации'),
        ),
        migrations.AlterField(
            model_name='activationkey',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
