# Generated by Django 3.2 on 2022-03-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0039_auto_20220317_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='activation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='catalogs.activationkey', verbose_name='Код активации'),
        ),
    ]
