# Generated by Django 3.2 on 2022-03-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0040_alter_device_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='activation_code',
            new_name='activation_key',
        ),
    ]
