# Generated by Django 4.0.4 on 2022-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0041_rename_activation_code_device_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='semi_product',
            field=models.BooleanField(default=False, verbose_name='Полуфабрикат'),
        ),
    ]
