# Generated by Django 4.0.4 on 2022-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0042_product_semi_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='store_semi_product',
            field=models.BooleanField(default=False, verbose_name='Хранит полуфабрикаты'),
        ),
    ]
