# Generated by Django 4.0.4 on 2022-06-18 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0043_storage_store_semi_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCell',
            fields=[
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_key', models.CharField(blank=True, max_length=36, verbose_name='Внешний ключ')),
            ],
            options={
                'verbose_name': 'Складская ячейка',
                'verbose_name_plural': 'Складские ячейки',
            },
        ),
        migrations.AlterModelOptions(
            name='activationkey',
            options={'verbose_name': 'Ключ активации', 'verbose_name_plural': 'Ключи активации'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='externalsource',
            options={'verbose_name': 'Внешний источник', 'verbose_name_plural': 'Внешние источники'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Линия производства', 'verbose_name_plural': 'Линии производства'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Оранизации'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Номенклаутра', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='typefactoryoperation',
            options={'verbose_name': 'Тип производственной операции', 'verbose_name_plural': 'Типы производственных операций'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
    ]
