# Generated by Django 4.0.4 on 2022-07-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0045_alter_storage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecell',
            name='barcode',
            field=models.CharField(default='-', max_length=100, verbose_name='Штрихкод'),
        ),
    ]
