# Generated by Django 4.0.4 on 2022-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0046_storagecell_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsource',
            name='external_key',
            field=models.CharField(max_length=1024, verbose_name='Внешний ключ'),
        ),
        migrations.AlterField(
            model_name='externalsource',
            name='number',
            field=models.CharField(max_length=1024, verbose_name='Номер'),
        ),
    ]
