# Generated by Django 4.0.4 on 2022-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0047_alter_externalsource_external_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linedevice',
            options={'verbose_name': 'Устройство линии', 'verbose_name_plural': 'Устройства линии'},
        ),
        migrations.AlterModelOptions(
            name='lineproduct',
            options={'verbose_name': 'Номенклатура линии', 'verbose_name_plural': 'Номенклатура линии'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.AddField(
            model_name='externalsource',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
