# Generated by Django 4.0.4 on 2022-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0048_alter_linedevice_options_alter_lineproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='not_marked',
            field=models.BooleanField(default=False, verbose_name='Немаркируемый'),
        ),
        migrations.AddField(
            model_name='storage',
            name='production_without_marking',
            field=models.BooleanField(default=False, verbose_name='Производство без маркировки'),
        ),
    ]
