# Generated by Django 4.0.4 on 2022-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0049_product_not_marked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variable_pallet_weight',
            field=models.BooleanField(default=False, verbose_name='Переменный вес паллеты'),
        ),
    ]
