# Generated by Django 4.0.4 on 2022-12-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0033_storagecell_remove_pallet_cell_alter_pallet_status_and_more'),
        ('catalogs', '0050_product_variable_pallet_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageCell',
        ),
    ]
