# Generated by Django 4.0.4 on 2023-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0051_delete_storagecell'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес'),
        ),
    ]
