# Generated by Django 4.0.4 on 2023-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0052_unit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='check_collect_pallet',
            field=models.BooleanField(default=True, verbose_name='Проверять собранные паллеты'),
        ),
    ]
