# Generated by Django 4.0.4 on 2023-08-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0053_line_check_collect_pallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterField(
            model_name='product',
            name='not_marked',
            field=models.BooleanField(default=False, verbose_name='Не маркируемый'),
        ),
    ]
