# Generated by Django 4.0.4 on 2023-12-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0055_product_service_check_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='interval_control_scanning_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Интервал запроса (в штуках)'),
        ),
        migrations.AddField(
            model_name='line',
            name='use_control_scanning_weight',
            field=models.BooleanField(default=False, verbose_name='Включить запрос весового ШК, для контроля веса товаров с фиксированным весом'),
        ),
    ]
