# Generated by Django 3.2 on 2021-09-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_of_shift', models.CharField(choices=[('MV', 'Перемещение'), ('MR', 'Маркировка'), ('IV', 'Инвентаризация')], default='MR', max_length=2)),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('unloaded', models.BooleanField(default=False, verbose_name='Выгружена')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(verbose_name='Дата выработки')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.line', verbose_name='Линия')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organization', verbose_name='Организация')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
