# Generated by Django 4.0.4 on 2022-10-27 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0050_product_variable_pallet_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('creating_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('batch_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер партии')),
                ('production_date', models.DateField(verbose_name='Дата выработки')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ГУИД')),
                ('code_offline', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ключ группы оффлайн')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
    ]
