# Generated by Django 3.2 on 2021-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftoperation',
            name='ready_to_unload',
            field=models.BooleanField(default=False, verbose_name='Готова к выгрузке'),
        ),
        migrations.AlterField(
            model_name='shiftoperation',
            name='type_of_shift',
            field=models.CharField(choices=[('MV', 'Перемещение'), ('MR', 'Маркировка'), ('IV', 'Инвентаризация')], default='MR', max_length=2, verbose_name='Тип смены'),
        ),
    ]
