# Generated by Django 4.0.4 on 2022-10-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0050_product_variable_pallet_weight'),
        ('factory_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product', verbose_name='Номенклатура')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_core.shift', verbose_name='Смена')),
            ],
        ),
    ]
