# Generated by Django 4.0.4 on 2022-10-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_core', '0002_shiftproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftproduct',
            options={'verbose_name': 'Номенклатура смен', 'verbose_name_plural': 'Номенклатура смен'},
        ),
    ]
