# Generated by Django 4.0.4 on 2023-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_core', '0004_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='type',
            field=models.CharField(choices=[('Маркируемая', 'Marked'), ('Не маркируемая', 'Unmarked'), ('Полуфабрикат', 'Semi Products')], default='Маркируемая', max_length=20, null=True, verbose_name='Тип'),
        ),
    ]
