# Generated by Django 4.0.4 on 2023-10-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0054_alter_product_options_alter_product_not_marked'),
        ('factory_core', '0006_alter_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='shift',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Номенклатура'),
        ),
    ]
